### PR TITLE
Authz headers handled and set as attributes for traces 

### LINKED ISSUE #336: Pass OAuth2 proxy authz headers to the plugin call
# Short Description of the issue

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

### PR DESCRIPTION
**Pull request by Bianco95**
The *SetupTelemetry* function has been updated to dynamically create a service with a unique name depending on whether it is invoked by the VK or the InterLink API. 
Additionally, information extracted from the AUTHZ headers is now included as attributes of the span associated with different HTTP calls.

### CODE REVIEW

File: pkg/interlink/config.go [hunk 1]
```diff
@@ -113,25 +109,24 @@ func SetupTelemetry(ctx context.Context) (*sdktrace.TracerProvider, error) {
 			Certificates:       []tls.Certificate{cert},
 			RootCAs:            certPool,
 			MinVersion:         tls.VersionTLS12,
-			InsecureSkipVerify: false,
+			InsecureSkipVerify: true, // #nosec
```
Comment (dciangot) [inline pkg/interlink/config.go]: why exactly? @Bianco95  :)

Comment (Bianco95) [reply pkg/interlink/config.go]: If the CA used for the mTLS mechanism is not verified by a trusted authority, an error occurred when a trace is sent to the Tempo endpoint, specifically
*2025/01/08 12:39:19 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority*

Comment (dciangot) [reply pkg/interlink/config.go]: alright, only if you open an issue where we track that this value should be passed as a configuration parameter :) it can go for a later time, but we need to keep track

Comment (Bianco95) [reply pkg/interlink/config.go]: Since this relates to telemetry configuration, I propose adding an environment variable, similar to how other telemetry parameters are handled. By default, *insecureSkipVerify* will be set to false, but users will have the option to override this and set it to true if needed.

Comment (dciangot) [reply pkg/interlink/config.go]: +1

**Comment by dciangot** [comment]
@Bianco95 can you document this env variable in the documenation of the monitoring as well?

**Comment by Bianco95** [comment]
Monitoring documentation has been properly updated

**Review by dciangot — APPROVED** [review]
Lgtm

**Comment by dciangot** [comment]
Although,  the integration test seems loke not working... need to check it carefully
